# dbn-go .goreleaser-mcp-data.yaml
# Separate goreleaser config for dbn-go-mcp-data (requires CGO for DuckDB).
# Per-platform builds with explicit cross-compilers.
#
# Usage:
#   goreleaser release --config .goreleaser-mcp-data.yaml

version: 2

builds:
  - id: "dbn-go-mcp-data-linux-amd64"
    main: ./cmd/dbn-go-mcp-data
    binary: bin/dbn-go-mcp-data
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++

  - id: "dbn-go-mcp-data-linux-arm64"
    main: ./cmd/dbn-go-mcp-data
    binary: bin/dbn-go-mcp-data
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++

  - id: "dbn-go-mcp-data-darwin-amd64"
    main: ./cmd/dbn-go-mcp-data
    binary: bin/dbn-go-mcp-data
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++

  - id: "dbn-go-mcp-data-darwin-arm64"
    main: ./cmd/dbn-go-mcp-data
    binary: bin/dbn-go-mcp-data
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      dbn-go-mcp-data_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums-mcp-data.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: NimbleMarkets
    name: dbn-go
