# dbn-go .goreleaser.yml
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run ./cmd/dbn-go-file completion bash > ./completions/dbn-go-file.bash'
    - sh -c 'go run ./cmd/dbn-go-file completion fish > ./completions/dbn-go-file.fish'
    - sh -c 'go run ./cmd/dbn-go-file completion zsh > ./completions/dbn-go-file.zsh'
    - sh -c 'go run ./cmd/dbn-go-file docs man -o ./manpages/'
    - sh -c 'go run ./cmd/dbn-go-hist completion bash > ./completions/dbn-go-hist.bash'
    - sh -c 'go run ./cmd/dbn-go-hist completion fish > ./completions/dbn-go-hist.fish'
    - sh -c 'go run ./cmd/dbn-go-hist completion zsh > ./completions/dbn-go-hist.zsh'
    - sh -c 'go run ./cmd/dbn-go-hist docs man -o ./manpages/'

builds:
  - id: "dbn-go-file"
    main: ./cmd/dbn-go-file
    binary: bin/dbn-go-file
    goos:
      - linux
      - darwin
      - windows

  - id: "dbn-go-hist"
    main: ./cmd/dbn-go-hist
    binary: bin/dbn-go-hist
    goos:
      - linux
      - darwin
      - windows

  - id: "dbn-go-live"
    main: ./cmd/dbn-go-live
    binary: bin/dbn-go-live
    goos:
      - linux
      - darwin
      - windows

  - id: "dbn-go-mcp-meta"
    main: ./cmd/dbn-go-mcp-meta
    binary: bin/dbn-go-mcp-meta
    goos:
      - linux
      - darwin
      - windows

  - id: "dbn-go-slurp-docs"
    main: ./cmd/dbn-go-slurp-docs
    binary: bin/dbn-go-slurp-docs
    goos:
      - linux
      - darwin
      - windows

  - id: "dbn-go-tui"
    main: ./cmd/dbn-go-tui
    binary: bin/dbn-go-tui
    goos:
      - linux
      - darwin
      - windows

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: ./manpages/*
        dst: man/man1/
        strip_parent: true
      - src: ./completions/*
        dst: completions/
        strip_parent: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: NimbleMarkets
    name: dbn-go

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - default
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

brews:
  - homepage: https://github.com/NimbleMarkets/dbn-go
    description: "Golang tooling for Databento's APIs and DBN format"
    directory: Formula
    repository:
      owner: NimbleMarkets
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@nimble.markets
    install: |
      bin.install "./bin/dbn-go-file"
      bin.install "./bin/dbn-go-hist"
      bin.install "./bin/dbn-go-live"
      bin.install "./bin/dbn-go-mcp-meta"
      bin.install "./bin/dbn-go-slurp-docs"
      bin.install "./bin/dbn-go-tui"
