version: '3'

tasks:
  default:
    desc: 'Default task is to "test" and "build"'
    deps:
      - test
      - build

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  build:
    desc: 'Build all'
    deps:
      - go-build

  test:
    desc: 'Test all'
    deps:
      - go-test

  clean:
    desc: 'Clean all'
    cmds:
      - rm -f bin/dbn-go-hist bin/dbn-go-live bin/dbn-go-tui

  docker-build:
    desc: 'Docker build'
    deps:
      - go-tidy
    cmds:
      - docker build .

###############################################################################

  go-tidy:
    desc: 'Tidy all'
    cmds:
      - go mod tidy

  go-update:
    desc: 'Update Go dependencies'
    cmds:
      - go get -u ./...

  go-build:
    desc: 'Build Go binaries'
    deps:
      - build-dbn-go-hist
      - build-dbn-go-live
      - build-dbn-go-tui

  build-dbn-go-hist:
    desc: 'Build dbn-go-hist'
    deps: [go-tidy]
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - cmd/dbn-go-hist/*.go
    generates:
      - bin/dbn-go-hist
    cmds:
      - go build -o bin/dbn-go-hist cmd/dbn-go-hist/*.go

  test-dbn-go-hist:
    desc: 'Test dbn-go-hist'
    deps: [build-dbn-go-hist]
    cmds:
      - DBN_GO_HIST=./bin/dbn-go-hist ./tests/exercise_dbn-go-hist.sh > /dev/null
      - echo $?

  build-dbn-go-live:
    desc: 'Build dbn-go-live'
    deps: [go-tidy]
    sources:
      - ./*.go
      - live/*.go
      - cmd/dbn-go-live/*.go
    generates:
      - bin/dbn-go-live
    cmds:
      - go build -o bin/dbn-go-live cmd/dbn-go-live/*.go

  build-dbn-go-tui:
    desc: 'Build dbn-go-tui'
    deps: [go-tidy]
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - cmd/dbn-go-tui/*.go
    generates:
      - bin/dbn-go-tui
    cmds:
      - go build -o bin/dbn-go-tui cmd/dbn-go-tui/*.go

  go-test:
    desc: 'Test Go'
    deps: [go-tidy]
    sources:
      - ./*.go
      - live/*.go
      - hist/*.go
      - cmd/dbn-go-hist/*.go
      - cmd/dbn-go-live/*.go
    cmds:
      - go test ./...

  go-test-no-api:
    desc: 'Test Go, but no API calls'
    deps: [go-tidy]
    cmds:
      - go test && go test ./live

###############################################################################
