version: '3'

tasks:
  default:
    desc: 'Default task is to "test" and "build"'
    deps:
      - test
      - build

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  build:
    desc: 'Build all'
    deps:
      - go-build

  test:
    desc: 'Test most'
    deps:
      - go-test

  test-all:
    desc: 'Test all'
    deps:
      - go-test
      - test-dbn-go-file
      - test-dbn-go-hist

  clean:
    desc: 'Clean all'
    cmds:
      - rm -f bin/dbn-go-file bin/dbn-go-hist bin/dbn-go-live bin/dbn-go-mcp bin/dbn-go-tui bin/dbn-go-slurp-docs
      - rm -rf docs-corpus slurped-docs

  docker-build:
    desc: 'Docker build'
    deps:
      - go-tidy
    cmds:
      - docker build .

###############################################################################

  go-tidy:
    desc: 'Tidy all'
    cmds:
      - go mod tidy
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - live/*.go
      - cmd/**/*.go

  go-update:
    desc: 'Update Go dependencies'
    cmds:
      - go get -u ./...

  go-build:
    desc: 'Build Go binaries'
    deps:
      - build-dbn-go-file
      - build-dbn-go-hist
      - build-dbn-go-live
      - build-dbn-go-mcp
      - build-dbn-go-tui
      - build-dbn-go-slurp-docs

  build-dbn-go-file:
    desc: 'Build dbn-go-file'
    deps: [go-tidy]
    sources:
      - ./*.go
      - internal/**/*.go
      - cmd/dbn-go-file/*.go
    generates:
      - bin/dbn-go-file
    cmds:
      - go build -o bin/dbn-go-file cmd/dbn-go-file/*.go

  build-dbn-go-hist:
    desc: 'Build dbn-go-hist'
    deps: [go-tidy]
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - cmd/dbn-go-hist/*.go
    generates:
      - bin/dbn-go-hist
    cmds:
      - go build -o bin/dbn-go-hist cmd/dbn-go-hist/*.go

  test-dbn-go-file:
    desc: 'Test dbn-go-file'
    deps: [build-dbn-go-file]
    cmds:
      - DBN_GO_FILE=./bin/dbn-go-file ./tests/exercise_dbn-go-file.sh
      - echo $?

  test-dbn-go-hist:
    desc: 'Test dbn-go-hist'
    deps: [build-dbn-go-hist]
    cmds:
      - DBN_GO_HIST=./bin/dbn-go-hist ./tests/exercise_dbn-go-hist.sh > /dev/null
      - echo $?

  build-dbn-go-live:
    desc: 'Build dbn-go-live'
    deps: [go-tidy]
    sources:
      - ./*.go
      - live/*.go
      - cmd/dbn-go-live/*.go
    generates:
      - bin/dbn-go-live
    cmds:
      - go build -o bin/dbn-go-live cmd/dbn-go-live/*.go

  build-dbn-go-mcp:
    desc: 'Build dbn-go-mcp'
    deps: [go-tidy]
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - cmd/dbn-go-mcp/*.go
    generates:
      - bin/dbn-go-mcp
    cmds:
      - go build -o bin/dbn-go-mcp cmd/dbn-go-mcp/*.go

  build-dbn-go-tui:
    desc: 'Build dbn-go-tui'
    deps: [go-tidy]
    sources:
      - ./*.go
      - hist/*.go
      - internal/**/*.go
      - cmd/dbn-go-tui/*.go
    generates:
      - bin/dbn-go-tui
    cmds:
      - go build -o bin/dbn-go-tui cmd/dbn-go-tui/*.go

  build-dbn-go-slurp-docs:
    desc: 'Build dbn-go-slurp-docs'
    deps: [go-tidy]
    sources:
      - cmd/dbn-go-slurp-docs/*.go
    generates:
      - bin/dbn-go-slurp-docs
    cmds:
      - go build -o bin/dbn-go-slurp-docs cmd/dbn-go-slurp-docs/*.go

  go-test:
    desc: 'Test Go'
    deps: [go-tidy]
    sources:
      - ./*.go
      - cmd/dbn-go-file/*.go
      - cmd/dbn-go-hist/*.go
      - cmd/dbn-go-live/*.go
      - cmd/dbn-go-mcp/*.go
      - cmd/dbn-go-tui/*.go
      - hist/*.go
      - internal/*.go
      - live/*.go
    cmds:
      - go test ./...

  go-test-no-api:
    desc: 'Test Go, but no API calls'
    deps: [go-tidy]
    cmds:
      - go test && go test ./live

###############################################################################

  docs-corpus-init:
    desc: 'Generate docs corpus directory structure (requires Chrome to generate sitemap)'
    deps: [build-dbn-go-slurp-docs]
    cmds:
      - ./bin/dbn-go-slurp-docs -generate-sitemap docs-corpus
      - ./bin/dbn-go-slurp-docs docs-corpus

  docs-corpus-fetch:
    desc: 'Fetch all docs content with Chrome (slow, ~15 minutes)'
    deps: [build-dbn-go-slurp-docs]
    cmds:
      - ./bin/dbn-go-slurp-docs -generate-sitemap -fetch docs-corpus

  docs-corpus-fetch-fast:
    desc: 'Fetch docs with shorter delays (may hit rate limits)'
    deps: [build-dbn-go-slurp-docs]
    cmds:
      - ./bin/dbn-go-slurp-docs -generate-sitemap -fetch -delay=1s -v docs-corpus

  docs-corpus-resume:
    desc: 'Resume fetching docs from where it left off'
    deps: [build-dbn-go-slurp-docs]
    cmds:
      - ./bin/dbn-go-slurp-docs -fetch docs-corpus

  docs-corpus-reset:
    desc: 'Reset docs corpus and start fresh (regenerates sitemap)'
    deps: [build-dbn-go-slurp-docs]
    cmds:
      - rm -rf docs-corpus
      - ./bin/dbn-go-slurp-docs -generate-sitemap -fetch -no-resume docs-corpus

