version: '3'

tasks:
  default:
    desc: 'Default task is to "test" and "build"'
    deps:
      - test
      - build

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  build:
    desc: 'Build all'
    deps:
      - go-build

  test:
    desc: 'Test all'
    deps:
      - go-test

  clean:
    desc: 'Clean'
    cmds:
      - rm -f bin/dbn-go-live

  docker-build:
    desc: 'Docker build'
    deps:
      - go-tidy
    cmds:
      - docker build .

###############################################################################

  go-tidy:
    desc: 'Tidy all'
    cmds:
      - go mod tidy

  go-update:
    desc: 'Update Go dependencies'
    cmds:
      - go get -u ./...

  go-build:
    desc: 'Build Go binaries'
    deps: [go-tidy]
    cmds:
      - go build -o bin/dbn-go-live cmd/dbn-go-live/*.go
    generates:
      - bin/dbn-go-live

  go-test:
    desc: 'Test Go'
    deps: [go-tidy]
    cmds:
      - go test ./...

  go-test-no-api:
    desc: 'Test Go, but no API calls'
    deps: [go-tidy]
    cmds:
      - go test && go test ./live

###############################################################################
