# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DATABENTO_API_KEY: ${{ secrets.DATABENTO_API_KEY }}
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Integration Tests
      if: ${{ env.DATABENTO_API_KEY != '' }}
      env:
        CGO_ENABLED: "1"
      run: |
        go test -v -tags=integration ./hist
        go build -o bin/dbn-go-hist ./cmd/dbn-go-hist
        DBN_GO_HIST=./bin/dbn-go-hist ./tests/exercise_dbn-go-hist.sh > /dev/null
        go build -o bin/dbn-go-mcp-meta ./cmd/dbn-go-mcp-meta
        go build -o bin/dbn-go-mcp-data ./cmd/dbn-go-mcp-data
        ./scripts/smoke-test-mcp.sh -q -a
